apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: volume-azurefile-storage-deployment
spec:
  template:
    metadata:
      labels:
        app: storagedemo
    spec:
      containers:
        - name: storagedemo
          image: nginx:latest
          volumeMounts:
            - name: azurefileshare
              mountPath: /storage
      volumes:
       - name: azurefileshare
         persistentVolumeClaim:
           claimName: pvc001
