apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "azpv0002"
spec:
  capacity:
    storage: "3Gi"
  accessModes:
    - "ReadWriteOnce"
  azureFile:
    secretName: azure-secret
    shareName: db02
    readOnly: false
