apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: ZGV2c3RyZzE0NTU=
  azurestorageaccountkey: aWZuWUMvNC9MS0VxcHlLZWhveVNsTFZQd1R5bUtKMUZkblYyZkloU0FXV2hKdEpCUG1ucEtQSHZjNjBPM1JRbzU5SVRQQ2QvbktDRlgwb05jKzAzcUE9PQ==
